//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.235.
// 
#pragma warning disable 1591

namespace SIGPA.BO.wsSigpaDigitalizador {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsConsultarProcessoSoap", Namespace="http://tempuri.org/")]
    public partial class WsConsultarProcesso : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback wsRealizarLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsConsultarProcessoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsConsultarProcesso() {
            this.Url = global::SIGPA.BO.Properties.Settings.Default.BO_wsSigpaDigitalizador_WsConsultarProcesso;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event wsRealizarLoginCompletedEventHandler wsRealizarLoginCompleted;
        
        /// <remarks/>
        public event wsConsultarProcessoCompletedEventHandler wsConsultarProcessoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsRealizarLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public wsINFOUsuario wsRealizarLogin(string pUser, string pSenha) {
            object[] results = this.Invoke("wsRealizarLogin", new object[] {
                        pUser,
                        pSenha});
            return ((wsINFOUsuario)(results[0]));
        }
        
        /// <remarks/>
        public void wsRealizarLoginAsync(string pUser, string pSenha) {
            this.wsRealizarLoginAsync(pUser, pSenha, null);
        }
        
        /// <remarks/>
        public void wsRealizarLoginAsync(string pUser, string pSenha, object userState) {
            if ((this.wsRealizarLoginOperationCompleted == null)) {
                this.wsRealizarLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsRealizarLoginOperationCompleted);
            }
            this.InvokeAsync("wsRealizarLogin", new object[] {
                        pUser,
                        pSenha}, this.wsRealizarLoginOperationCompleted, userState);
        }
        
        private void OnwsRealizarLoginOperationCompleted(object arg) {
            if ((this.wsRealizarLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsRealizarLoginCompleted(this, new wsRealizarLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsConsultarProcesso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public wsINFOCliente wsConsultarProcesso(string pNumeroProcesso) {
            object[] results = this.Invoke("wsConsultarProcesso", new object[] {
                        pNumeroProcesso});
            return ((wsINFOCliente)(results[0]));
        }
        
        /// <remarks/>
        public void wsConsultarProcessoAsync(string pNumeroProcesso) {
            this.wsConsultarProcessoAsync(pNumeroProcesso, null);
        }
        
        /// <remarks/>
        public void wsConsultarProcessoAsync(string pNumeroProcesso, object userState) {
            if ((this.wsConsultarProcessoOperationCompleted == null)) {
                this.wsConsultarProcessoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsConsultarProcessoOperationCompleted);
            }
            this.InvokeAsync("wsConsultarProcesso", new object[] {
                        pNumeroProcesso}, this.wsConsultarProcessoOperationCompleted, userState);
        }
        
        private void OnwsConsultarProcessoOperationCompleted(object arg) {
            if ((this.wsConsultarProcessoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsConsultarProcessoCompleted(this, new wsConsultarProcessoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class wsINFOUsuario {
        
        private string nomeUsuarioField;
        
        private string perfilUsuarioField;
        
        /// <remarks/>
        public string NomeUsuario {
            get {
                return this.nomeUsuarioField;
            }
            set {
                this.nomeUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string PerfilUsuario {
            get {
                return this.perfilUsuarioField;
            }
            set {
                this.perfilUsuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class wsINFOCliente {
        
        private int idProcessoSigpaField;
        
        private int idClienteField;
        
        private string nomeMapaField;
        
        private string nomeClienteField;
        
        private string numeroCPFField;
        
        private string numeroCNPJField;
        
        /// <remarks/>
        public int IdProcessoSigpa {
            get {
                return this.idProcessoSigpaField;
            }
            set {
                this.idProcessoSigpaField = value;
            }
        }
        
        /// <remarks/>
        public int IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMapa {
            get {
                return this.nomeMapaField;
            }
            set {
                this.nomeMapaField = value;
            }
        }
        
        /// <remarks/>
        public string NomeCliente {
            get {
                return this.nomeClienteField;
            }
            set {
                this.nomeClienteField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroCPF {
            get {
                return this.numeroCPFField;
            }
            set {
                this.numeroCPFField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroCNPJ {
            get {
                return this.numeroCNPJField;
            }
            set {
                this.numeroCNPJField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void wsRealizarLoginCompletedEventHandler(object sender, wsRealizarLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsRealizarLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsRealizarLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsINFOUsuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsINFOUsuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void wsConsultarProcessoCompletedEventHandler(object sender, wsConsultarProcessoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsConsultarProcessoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsConsultarProcessoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsINFOCliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsINFOCliente)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591