///////////////////////////////////////////////////////////
//  INFODocumento.cs
//  Implementation of the Class INFODocumento
//  Generated by Enterprise Architect
//  Created on:      06-ago-2010 22:24:34
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Collections;


namespace SIGPA.INFO {
	public class INFODocumento {

		private double iddocumentos;
		private string nomedocumento;
        private INFOTipoDocumento objTipoDocumento;
		private List<INFOProcesso> objProcesso;

		public INFODocumento(){

		}

		~INFODocumento(){

		}

		public virtual void Dispose(){

		}

		public double IdDocumentos{
			get{
				return iddocumentos;
			}
			set{
				iddocumentos = value;
			}
		}

		public string NomeDocumento{
			get{
				return nomedocumento;
			}
			set{
				nomedocumento = value;
			}
		}

		public List<INFOProcesso> ObjProcesso{
			get{
				return objProcesso;
			}
			set{
				objProcesso = value;
			}
		}

        public INFOTipoDocumento ObjTipoDocumento
        {
            get { return objTipoDocumento; }
            set { objTipoDocumento = value; }
        }

	}//end INFODocumento

}//end namespace INFO