///////////////////////////////////////////////////////////
//  INFOHistorico.cs
//  Implementation of the Class INFOHistorico
//  Generated by Enterprise Architect
//  Created on:      06-ago-2010 22:24:34
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Collections;
using System;

namespace SIGPA.INFO {
	public class INFOHistorico {

		private double idhistorico;
		private DateTime datahistorico;
		private string descricaooperacao;
		private string nomeusuarioresponsavel;
		private INFODocumentoDigital objdocumentodigital;

		public INFOHistorico(){

		}

		~INFOHistorico(){

		}

		public virtual void Dispose(){

		}

		public DateTime DataHistorico{
			get{
				return datahistorico;
			}
			set{
				datahistorico = value;
			}
		}

		public string DescricaoOperacao{
			get{
				return descricaooperacao;
			}
			set{
				descricaooperacao = value;
			}
		}

		public double IdHistorico{
			get{
				return idhistorico;
			}
			set{
				idhistorico = value;
			}
		}

		public string NomeUsuarioResponsavel{
			get{
				return nomeusuarioresponsavel;
			}
			set{
				nomeusuarioresponsavel = value;
			}
		}

		public INFODocumentoDigital ObjDocumentoDigital{
			get{
				return objdocumentodigital;
			}
			set{
				objdocumentodigital = value;
			}
		}

	}//end INFOHistorico

}//end namespace INFO