///////////////////////////////////////////////////////////
//  INFOProcesso.cs
//  Implementation of the Class INFOProcesso
//  Generated by Enterprise Architect
//  Created on:      06-ago-2010 22:24:34
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Collections;



namespace SIGPA.INFO {
	public class INFOProcesso {

		private double idprocesso;
		private string numeroreferencia;
		private List<INFODocumento> objDocumento;
        private INFOCliente objcliente;
		private INFODocumento objdocumento;
        private double idprocessosigpa;

		public INFOProcesso(){

		}

		~INFOProcesso(){

		}

		public virtual void Dispose(){

		}

		public double IdProcesso{
			get{
				return idprocesso;
			}
			set{
				idprocesso = value;
			}
		}

		public string NumeroReferencia{
			get{
				return numeroreferencia;
			}
			set{
				numeroreferencia = value;
			}
		}

		public List<INFODocumento> ObjDocumento{
			get{
				return objDocumento;
			}
			set{
				objDocumento = value;
			}
		}

        public INFOCliente ObjCliente
        {
            get { return objcliente; }
            set { objcliente = value; }
        }

        public double IdProcessoSigpa
        {
            get { return idprocessosigpa; }
            set { idprocessosigpa = value; }
        }
	}//end INFOProcesso

}//end namespace INFO