///////////////////////////////////////////////////////////
//  INFOCliente.cs
//  Implementation of the Class INFOCliente
//  Generated by Enterprise Architect
//  Created on:      06-ago-2010 22:24:34
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Collections;


namespace SIGPA.INFO {
	public class INFOCliente {

		private double idcliente;
		private string nomecliente;
		private string nomeclientemapa;
		private string numerocnpj;
		private string numerocpf;
        private double idclientesigpa;
		private List<INFOProcesso> objProcesso;

		public INFOCliente(){

		}

		~INFOCliente(){

		}

		public virtual void Dispose(){

		}

		public double IdCliente{
			get{
				return idcliente;
			}
			set{
				idcliente = value;
			}
		}

		public string NomeCliente{
			get{
				return nomecliente;
			}
			set{
				nomecliente = value;
			}
		}

		public string NomeClienteMapa{
			get{
				return nomeclientemapa;
			}
			set{
				nomeclientemapa = value;
			}
		}

		public string NumeroCnpj{
			get{
				return numerocnpj;
			}
			set{
				numerocnpj = value;
			}
		}

		public string NumeroCpf{
			get{
				return numerocpf;
			}
			set{
				numerocpf = value;
			}
		}

		public List<INFOProcesso> ObjProcesso{
			get{
				return objProcesso;
			}
			set{
				objProcesso = value;
			}
		}

        public double IdClienteSigpa
        {
            get { return idclientesigpa; }
            set { idclientesigpa = value; }
        }
  

	}//end INFOCliente

}//end namespace INFO