///////////////////////////////////////////////////////////
//  INFODocumentoDigital.cs
//  Implementation of the Class INFODocumentoDigital
//  Generated by Enterprise Architect
//  Created on:      06-ago-2010 22:24:34
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Collections;

namespace SIGPA.INFO {
	public class INFODocumentoDigital {

		private double iddocumentodigital;
		private string nomearquivo;
		private string nomediretorioarquivo;
        private double idDocumento;
        private double idProcesso;

		public INFOHistorico objHistorico;

		public INFODocumentoDigital(){

		}

		~INFODocumentoDigital(){

		}

		public virtual void Dispose(){

		}


        public double IdDocumento
        {
            get { return idDocumento; }
            set { idDocumento = value; }
        }
        public double IdProcesso
        {
            get { return idProcesso; }
            set { idProcesso = value; }
        }

		public double IdDocumentoDigital{
			get{
				return iddocumentodigital;
			}
			set{
				iddocumentodigital = value;
			}
		}

		public string NomeArquivo{
			get{
				return nomearquivo;
			}
			set{
				nomearquivo = value;
			}
		}

		public string NomeDiretorioArquivo{
			get{
				return nomediretorioarquivo;
			}
			set{
				nomediretorioarquivo = value;
			}
		}

	}//end INFODocumentoDigital

}//end namespace INFO