//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace PMNC.MonitoramentoPainel {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsPainelOperacionalSoap", Namespace="http://tempuri.org/")]
    public partial class wsPainelOperacional : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback obterNaviosAtracadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback obterRSSParaOMonitorOperationCompleted;
        
        private System.Threading.SendOrPostCallback obterAniversariantesOperationCompleted;
        
        private System.Threading.SendOrPostCallback obterComunicadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback obterCotacaoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsPainelOperacional() {
            this.Url = global::PMNC.Properties.Settings.Default.PMNC_MonitoramentoPainel_wsPainelOperacional;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event obterNaviosAtracadosCompletedEventHandler obterNaviosAtracadosCompleted;
        
        /// <remarks/>
        public event obterRSSParaOMonitorCompletedEventHandler obterRSSParaOMonitorCompleted;
        
        /// <remarks/>
        public event obterAniversariantesCompletedEventHandler obterAniversariantesCompleted;
        
        /// <remarks/>
        public event obterComunicadosCompletedEventHandler obterComunicadosCompleted;
        
        /// <remarks/>
        public event obterCotacaoCompletedEventHandler obterCotacaoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obterNaviosAtracados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string obterNaviosAtracados() {
            object[] results = this.Invoke("obterNaviosAtracados", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void obterNaviosAtracadosAsync() {
            this.obterNaviosAtracadosAsync(null);
        }
        
        /// <remarks/>
        public void obterNaviosAtracadosAsync(object userState) {
            if ((this.obterNaviosAtracadosOperationCompleted == null)) {
                this.obterNaviosAtracadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobterNaviosAtracadosOperationCompleted);
            }
            this.InvokeAsync("obterNaviosAtracados", new object[0], this.obterNaviosAtracadosOperationCompleted, userState);
        }
        
        private void OnobterNaviosAtracadosOperationCompleted(object arg) {
            if ((this.obterNaviosAtracadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obterNaviosAtracadosCompleted(this, new obterNaviosAtracadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obterRSSParaOMonitor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string obterRSSParaOMonitor() {
            object[] results = this.Invoke("obterRSSParaOMonitor", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void obterRSSParaOMonitorAsync() {
            this.obterRSSParaOMonitorAsync(null);
        }
        
        /// <remarks/>
        public void obterRSSParaOMonitorAsync(object userState) {
            if ((this.obterRSSParaOMonitorOperationCompleted == null)) {
                this.obterRSSParaOMonitorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobterRSSParaOMonitorOperationCompleted);
            }
            this.InvokeAsync("obterRSSParaOMonitor", new object[0], this.obterRSSParaOMonitorOperationCompleted, userState);
        }
        
        private void OnobterRSSParaOMonitorOperationCompleted(object arg) {
            if ((this.obterRSSParaOMonitorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obterRSSParaOMonitorCompleted(this, new obterRSSParaOMonitorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obterAniversariantes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string obterAniversariantes() {
            object[] results = this.Invoke("obterAniversariantes", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void obterAniversariantesAsync() {
            this.obterAniversariantesAsync(null);
        }
        
        /// <remarks/>
        public void obterAniversariantesAsync(object userState) {
            if ((this.obterAniversariantesOperationCompleted == null)) {
                this.obterAniversariantesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobterAniversariantesOperationCompleted);
            }
            this.InvokeAsync("obterAniversariantes", new object[0], this.obterAniversariantesOperationCompleted, userState);
        }
        
        private void OnobterAniversariantesOperationCompleted(object arg) {
            if ((this.obterAniversariantesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obterAniversariantesCompleted(this, new obterAniversariantesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obterComunicados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string obterComunicados() {
            object[] results = this.Invoke("obterComunicados", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void obterComunicadosAsync() {
            this.obterComunicadosAsync(null);
        }
        
        /// <remarks/>
        public void obterComunicadosAsync(object userState) {
            if ((this.obterComunicadosOperationCompleted == null)) {
                this.obterComunicadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobterComunicadosOperationCompleted);
            }
            this.InvokeAsync("obterComunicados", new object[0], this.obterComunicadosOperationCompleted, userState);
        }
        
        private void OnobterComunicadosOperationCompleted(object arg) {
            if ((this.obterComunicadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obterComunicadosCompleted(this, new obterComunicadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obterCotacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string obterCotacao() {
            object[] results = this.Invoke("obterCotacao", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void obterCotacaoAsync() {
            this.obterCotacaoAsync(null);
        }
        
        /// <remarks/>
        public void obterCotacaoAsync(object userState) {
            if ((this.obterCotacaoOperationCompleted == null)) {
                this.obterCotacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobterCotacaoOperationCompleted);
            }
            this.InvokeAsync("obterCotacao", new object[0], this.obterCotacaoOperationCompleted, userState);
        }
        
        private void OnobterCotacaoOperationCompleted(object arg) {
            if ((this.obterCotacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obterCotacaoCompleted(this, new obterCotacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void obterNaviosAtracadosCompletedEventHandler(object sender, obterNaviosAtracadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obterNaviosAtracadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obterNaviosAtracadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void obterRSSParaOMonitorCompletedEventHandler(object sender, obterRSSParaOMonitorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obterRSSParaOMonitorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obterRSSParaOMonitorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void obterAniversariantesCompletedEventHandler(object sender, obterAniversariantesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obterAniversariantesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obterAniversariantesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void obterComunicadosCompletedEventHandler(object sender, obterComunicadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obterComunicadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obterComunicadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void obterCotacaoCompletedEventHandler(object sender, obterCotacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obterCotacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obterCotacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591